package enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum Countries {
    ITALY("Italy"),
    GERMANY("Germany"),
    SPAIN("Spain"),
    FRANCE("France"),
    UKRAINE("Ukraine"),
    POLAND("Poland"),
    ESTONIA("Estonia"),
    ROME("Rome"),
    PARIS("Paris"),
    BERLIN("Berlin"),
    HAMBURG("Hamburg"),
    CHINA("China"),
    CANADA("Canada"),
    NEW_YORK_CITY("New York"),
    ANGOLA("Angola"),
    NEW_JERSEY("New Jersey"),
    QATAR("Quatar"),
    SAINT_PETERSBURG("Saint Petersburg"),
    CEYLON("Ceylon"),
    SUDAN("Sudan"),
    MALAYSIA("Malaysia"),
    ROMANIA("Romania"),
    GREAT_BRITAIN("Great Britain"),
    UNITED_KINGDOM("United Kingdom"),
    UNITED_STATES("United States"),
    TEXAS("Texas"),
    OHIO("Ohio"),
    PAKISTAN("Pakistan"),
    GEORGIA("Georgia"),
    CAMBODIA("Cambodia"),
    VOLGOGRAD("Volgograd"),
    NEW_YORK("New York"),
    UGANDA("Uganda"),
    PORTUGAL("Portugal"),
    LISABON("Lisabon"),
    PHUKET("Phuket"),
    MAROC("Maroc"),
    SHARGOROD("Shargorod"),
    KYIV("Kyiv"),
    MEXICO("Mexico"),
    SAN_DIEGO("San Diego"),
    DALLAS("Dallas"),
    CUBA("Cuba"),
    GUATEMALA("Guatemala"),
    CHILE("Chile"),
    PERU("Peru"),
    BOLIVIA("Bolivia"),
    PARAGUAY("Paraguay"),
    URUGUAY("Uruguay"),
    ARGENTINA("Argentina"),
    CHAD("Chad"),
    ALGERIA("Algeria"),
    SOUTH_AFRICA("South Africa"),
    MADAGASCAR("Madagascar"),
    ZIMBABWE("Zimbabwe"),
    TANZANIA("Tanzania"),
    MOZAMBIQUE("Mozambique"),
    KENYA("Kenya"),
    SOMALI("Somali"),
    GHANA("Ghana"),
    MAURITANIA("Mauritania"),
    MALI("Mali"),
    GABON("Gabon"),
    OMAN("Oman"),
    YEMEN("Yemen"),
    AUSTRALIA("Australia"),
    SYDNEY("Sydney"),
    TURKEY("Turkey"),
    ROMAN_REPUBLIC("Roman Republic"),
    MONGOLIA("Mongolia"),
    SWEDEN("Sweden"),
    BURMA("Burma"),
    BELEM("Belém"),
    SICILY("Sicily"),
    PALERMO("Palermo");

    public String countryName;
}
